<body class="d-flex justify-content-center align-items-center">
<main class="container-xl p-0 shadow-lg d-flex flex-xl-row flex-column">
  <section class="banner d-flex justify-content-center align-items-center">
    <div class="container-content-banner container-fluid w-75">
      <div class="container-banner-title d-flex justify-content-center"><h1 class="fs-4">Bem vindo!</h1></div>
      <div class="container-banner-text d-flex justify-content-center"><p class="text-center fs-6">Faça login e venha ser tratado pelos melhores do país!</p></div>
      <div class="container-banner-button d-flex justify-content-center"><button target="button" class="btn-login btn px-3 py-2 fs-6 fw-bold">Login</button></div>
    </div>
  </section>
  <section class="container-login container-fluid d-flex justify-content-center align-items-center">
    <div class="container-content-create container-fluid w-75 justify-content-center align-items-center"> 
      
    <div class="container-create-title"><h2 class="fs-4 text-center fw-bold">Criar conta</h2></div>
      <div class="container-create-text"><p class="fs-6">Crie a sua conta e venha ser tratado pelos melhores do país!</p></div>
    
      <form action="/home" method="post" class="d-flex gap-1 flex-column">

        <label for="inputName5" class="form-label my-1">Nome</label>
        <input type="name" id="inputName5" class="form-control" aria-describedby="NameHelpBlock">
        
        <label for="inputEmail5" class="form-label my-1">Email</label>
        <input type="email" id="inputEmail5" class="form-control" aria-describedby="emailHelpBlock">
        
        <label for="inputPassword5" class="form-label my-1">Password</label>
        <input type="password" id="inputPassword5" class="form-control mb-2" aria-describedby="passwordHelpBlock">

        <button class="btn btn-create fw-bold">Cadastre-se</button>
      </form>
    </div>
  </section>
</main>
</body>
