<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../css/requests.css">
  <link rel="stylesheet" href="../css/top.css">
  <link rel="stylesheet" href="../css/footer.css">
  <title>Requests</title>
</head>
<body>
  <main class="w-100">
    <section class="w-100 sectionPedidosRequest">
      <div class="container py-2">
        <div class="container-title py-2">
          <h1 class="fs-1 textTitle text-center">Faça seu pedido</h1>
        </div>

        <div class="w-100 d-flex flex-row flex-wrap container-all-cards gap-5 align-self-start justify-content-center">

          <div class="card align-self-start">
            <div div class="container-img">
              <img src="../images/ChocoVanillaBliss.jpg" class="card-img-top" alt="...">
            </div>
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/ChocolateCookieCup.jpg" class="card-img-top rounded imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/ChocoChantBrownieDelight.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>


          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/StrawberryDreamFloat.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/BerryBlissGelatoTart.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/ChocoCookieChantillyCup.jpg" class="card-img-top imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/RainbowBlissGelato.jpg" class="card-img-top imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/TripleTreatDelight.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/Casquinha.jpg" class="card-img-top imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
              <form action=""><a href="#" class="btn btn-addCar">Adicionar na compra</a></form>
            </div>
          </div>


        </div>
         
      </div>
    </section>
  </main>

<script src="../script/requests.js"></script>
</body>
</html>

<div class="d-none">
<div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="../images/ChocoVanillaBliss.jpg" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  
                  <div class="d-flex flex-column gap-2 flex-md-row justify-content-between pb-2">
                    <h5 class="card-title textTitle m-0">Choco Vanilla Bliss</h5>
                    <form action="" class="d-none d-md-block">
                      <button class="btn p-0 btn-addCar px-2">Adicionar no carrinho</button>
                    </form>
                  </div>
                  
                  <p class="card-text">Desfrute do ChocoVanillaBliss: uma explosão de sabor com a irresistível combinação de sorvete de baunilha mergulhado em uma cascata de chocolate. Cada colherada é uma jornada sensorial de prazer, onde a suavidade da baunilha se encontra com a riqueza do chocolate, proporcionando uma experiência verdadeiramente divina.</p>
                  <p class="card-text"><small class="text-body-secondary">Tempo de preparação 2 Minutos.</small></p>
                  <form action="" class="d-block d-md-none">
                      <button class="btn p-0 btn-addCar px-2">Adicionar no carrinho</button>
                  </form>
                </div>
              </div>
            </div>
          </div>

          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="../images/ChocolateCookieCup.jpg" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  
                  <div class="d-flex flex-row justify-content-between pb-2">
                    <h5 class="card-title textTitle m-0">Choco Vanilla Bliss</h5>
                    <form action="" class="d-none d-md-block">
                      <button class="btn p-0 btn-addCar px-2">Adicionar no carrinho</button>
                    </form>
                  </div>
                  
                  <p class="card-text">Desfrute do ChocoVanillaBliss: uma explosão de sabor com a irresistível combinação de sorvete de baunilha mergulhado em uma cascata de chocolate. Cada colherada é uma jornada sensorial de prazer, onde a suavidade da baunilha se encontra com a riqueza do chocolate, proporcionando uma experiência verdadeiramente divina.</p>
                  <p class="card-text"><small class="text-body-secondary">Tempo de preparação 2 Minutos.</small></p>
                  <form action="" class="d-block d-md-none">
                      <button class="btn p-0 btn-addCar px-2">Adicionar no carrinho</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
</div>