<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../css/requests.css">
  <link rel="stylesheet" href="../css/top.css">
  <link rel="stylesheet" href="../css/footer.css">
  <title>Requests</title>
</head>
<body>
  <main class="w-100">
    <section class="w-100 sectionPedidosRequest">
      <div class="container py-2">
        <div class="container-title py-2">
          <h1 class="fs-1 textTitle text-center">Faça seu pedido</h1>
        </div>

        <div class="w-100 d-flex flex-row flex-wrap container-all-cards gap-5 align-self-start justify-content-center">

          <div class="card align-self-start">
            <div div class="container-img">
              <img src="../images/ChocoVanillaBliss.jpg" class="card-img-top" alt="...">
            </div>
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Choco Vanilla Bliss</h5>
              <p class="card-text">Desfrute de uma explosão de sabor com o Choco Vanilla Bliss, onde a suavidade da baunilha se encontra com a riqueza do chocolate.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('ChocoVanillaBliss')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/ChocolateCookieCup.jpg" class="card-img-top rounded imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Chocolate Cookie Cup</h5>
              <p class="card-text">Delicie-se com o Chocolate Cookie Cup, uma combinação irresistível de chocolate e biscoitos crocantes.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('ChocolateCookieCup')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/ChocoChantBrownieDelight.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Choco Chant Brownie Delight</h5>
              <p class="card-text">Deleite-se com o Choco Chant Brownie Delight, uma harmonia perfeita entre brownie e chantilly de chocolate.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('ChocoChantBrownieDelight')">Adicionar na compra</button>
            </div>
          </div>


          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/StrawberryDreamFloat.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Strawberry Dream Float</h5>
              <p class="card-text">Surpreenda-se com o Strawberry Dream Float, uma viagem refrescante ao sabor das frutas vermelhas.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('StrawberryDreamFloat')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/BerryBlissGelatoTart.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Berry Bliss Gelato Tart</h5>
              <p class="card-text">Delicie-se com o Berry Bliss Gelato Tart, onde o gelato cremoso encontra o sabor intenso das frutas silvestres.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('BerryBlissGelatoTart')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/ChocoCookieChantillyCup.jpg" class="card-img-top imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Choco Cookie Chantilly Cup</h5>
              <p class="card-text">Saboreie o Choco Cookie Chantilly Cup, uma indulgência irresistível de chocolate, cookies e chantilly.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('ChocoCookieChantillyCup')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/RainbowBlissGelato.jpg" class="card-img-top imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Rainbow Bliss Gelato</h5>
              <p class="card-text">Deixe-se levar pelo arco-íris de sabores com o Rainbow Bliss Gelato.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('RainbowBlissGelato')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="container-img">
              <img src="../images/TripleTreatDelight.jpg" class="card-img-top" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Triple Treat Delight</h5>
              <p class="card-text">Mergulhe na felicidade com o Triple Treat Delight, uma explosão de sabores em cada colherada.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('TripleTreatDelight')">Adicionar na compra</button>
            </div>
          </div>

          <div class="card align-self-start">
            <div class="over container-img">
              <img src="../images/Casquinha.jpg" class="card-img-top imgHidden" alt="...">
            </div>
          
            <div class="card-body">
              <h5 class="card-title textTitle fs-4">Casquinha</h5>
              <p class="card-text">Para uma experiência clássica, saboreie uma deliciosa Casquinha, o toque perfeito para momentos doces e especiais.</p>
              <p class="card-text"><small class="text-body-secondary">Feito em 2 minutos</small></p>
             <button class="btn btn-addCar" onclick="carrinho.adicionarProdutos('Casquinha')">Adicionar na compra</button>
            </div>
          </div>


        </div>
         
      </div>
    </section>
  </main>

<script src="../script/requests.js"></script>
</body>
</html>

<button type="button" class="btn d-none carrinhoBtn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
  Abrir Carrinho
  <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
    <span class="visually-hidden">New alerts</span>
  </span>
</button>


<div class="offcanvas offcanvas-start canvasCar" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title textTitle fs-3" id="offcanvasScrollingLabel">Seu Carrinho <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shopping-cart"><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"/></svg></h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body position-relative">

    <button class="btn btnRealizarPedido" onclick="carrinho.fazerPedido()">Fazer pedido</button>
  </div>
</div>