<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>
		<link rel="stylesheet" href="layout1.css">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

		<style>	

			:root{ 
				--font: "Open Sans", sans-serif;
			}

			*{
				font-family: var(--font);
			}

			body{
				background-color: #EDEDED;
			}
			nav.navbar {
				background-color: #EDEDED!important;
			}
			
			a.btn{
				color: white;
			}

			a.active{
				background-color: #8c2519!important; 
			}

			.nav-item{
				margin: 0px!important;
				border-bottom: 2px solid #8c2519!important;
			}

			.nav-link{
				border-bottom: 2px solid #8c2519!important;
			}

			.menu{
				padding-top: 10px;
			}

			.menucontainer{
				border-bottom: 2px solid #8c2519!important;
			}

			ul.nav-tabs{
  			
			}

		</style>

	</head>

	<body>
	

	<?php	require 'topo.phtml';?>
		<?= $this->content() ?>
	<?php	require 'footer.phtml';?>
	</body>

</html>