<script src="/script/top.js"></script>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-xl">
    <a class="navbar-brand fs-2" href="/home">Frosty Delights</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link fs-5" aria-current="page" href="#">Home</a>
        <p class="fs-4 m-0 d-none d-xl-block">|</p>
        <a class="nav-link fs-5" href="#">Features</a>
        <p class="fs-4 m-0 d-none d-xl-block">|</p>
        <a class="nav-link fs-5" href="#">Pricing</a>
      </div>
    </div>
  </div>
</nav>
