<script src="/script/top.js"></script>
<nav class="navbar fixed-top bg-body-tertiary pb-0">
  <div class="container-top pb-md-2 w-100 container-sm justify-content-center">
    <h1>Frosty Delights</h1>
    <div class="d-flex containersobre">
      <a href="/sair" type="button" class="btn fs-6 sobre">Sobre o site</a>
    </div>
  </div>
  <div class="px-md-5 w-100 container-sm menucontainer">
    <div class="p-0 d-flex container-fluid menu flex-row align-items-end">
      
      <div onclick="abrirOpt(event)" class="text-decoration-none rounded-top p-2  w-25 d-flex 
      justify-content-center responsive-font align-items-center text-center opt fw-bold">Nossos sabores</div>
      
      <span class="mx-md-3 m-1 d-inline-block"></span>
      
      <div onclick="abrirOpt(event)" class="rounded-top text-center p-2  w-25 d-flex justify-content-center responsive-font align-items-center text-center opt fw-bold">Promoções</div>
     
      <span class="mx-md-3 m-1 d-inline-block"></span>
      
      <div onclick="abrirOpt(event)" class="rounded-top p-2  w-25 d-flex justify-content-center responsive-font text-center align-items-center text-center opt fw-bold">Pedidos</div>
      
      <span class="mx-md-3 m-1 my-1 d-inline-block"></span>
      
      <div onclick="abrirOpt(event)" class="rounded-top text-center p-2  w-25 d-flex justify-content-center responsive-font align-items-center text-center opt fw-bold">Contato</div>
    
    </div>
  </div>  
</nav>
